services:
  - type: web
    name: castora-backend-3
    runtime: python
    plan: 0.5c-512mb
    buildCommand: pip install -r requirements.txt
    startCommand: bash start_render.sh
    healthCheckPath: /healthz
    disk:
      name: castora-runtime
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: CASTORA_RUNTIME_DIR
        value: /var/data
      - key: REDIS_URL
        fromService:
          name: castora-queue
          type: keyvalue
          property: connectionString
      - key: GROQ_API_KEY
        sync: false
      - key: ELEVENSLAB_API_KEY
        sync: false
      - key: PODCAST_STUDIO_USE_REAL_TTS
        value: "true"
      - key: PODCAST_STUDIO_USE_AI_SCRIPT
        value: "true"

  - type: keyvalue
    name: castora-queue
    plan: free
    ipAllowList: []
    maxmemoryPolicy: noeviction
